&nbsp;<font color="#FFFFFF">| 
            <a href="result_chlogin.php">หน้าหลัก</a> | <a href="patient_search.php">ค้นหาผู้ป่วย</a> | 
			<a href="javascript:window.print()">พิมพ์</a> | <a href="index.php">ออกจากระบบ</a> | 
			<a href="javascript:onClick=Minimize()">ย่อหน้าต่าง</a> | <a href="javascript:history.back(-1)">ย้อนกลับ</a> |
			<a href="#closeform">ปิดหน้าต่าง</a> | <a href="about.php">About</a> |
			</font>